AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for EMR Cluster and ElasticSearch (OpenSearch)

Parameters:
  paramESPassword:
    Type: String
  paramKmsKey:
    Type: String

Resources:
  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: TwitterSentimentCluster
      ReleaseLabel: emr-6.5.0
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
      LogUri: s3://aws-logs-emr/elasticmapreduce/
      Applications:
        - Name: Spark
      Instances:
        KeepJobFlowAliveWhenNoSteps: true
        Ec2KeyName: emr_key
        CoreInstanceGroup:
          InstanceCount: 2
          InstanceType: m5.xlarge
          Market: ON_DEMAND
          Name: coreGroup
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
          Market: ON_DEMAND
          Name: masterGroup
  ESCluster:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: twitter-es
      ClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: '1'
        ZoneAwarenessEnabled: false
        InstanceType: 't3.small.search'
      EBSOptions:
        EBSEnabled: true
        Iops: '0'
        VolumeSize: '10'
        VolumeType: 'gp2'
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: opensearch_admin
          MasterUserPassword: !Ref paramESPassword
      NodeToNodeEncryptionOptions:
        Enabled: true
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: !Ref paramKmsKey
      DomainEndpointOptions:
        EnforceHTTPS: true
        CustomEndpointEnabled: false
      AdvancedOptions:
        override_main_response_version: true
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - "*"
            Action:
              - "es:*"
            Resource: "*"

Outputs:
  EMRClusterName:
    Description: EMR Cluster Name
    Value: !Ref EMRCluster
    Export:
      Name: !Sub "${AWS::StackName}-emrcluster"
  ESEndpoint:
    Description: ES Endpoint
    Value: !GetAtt ESCluster.DomainEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-esendpoint"