AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for EMR Cluster and ElasticSearch (OpenSearch)

Parameters:
  paramStepPath:
    Type: String
  paramServerStack:
    Type: String

Resources:
  EMRStep:
    Type: AWS::EMR::Step
    Properties:
      Name: TwitterSentiment
      ActionOnFailure: CANCEL_AND_WAIT
      JobFlowId: !ImportValue
        'Fn::Sub': '${paramServerStack}-emrcluster'
      HadoopJarStep:
        Jar: command-runner.jar
        Args:
          - spark-submit
          - --deploy-mode
          - cluster
          - --files
          - s3://twitter.model.resources/twitter_sentiment.app.properties
          - --class
          - br.com.geekfox.twitter.sentiment.App
          - !Ref paramStepPath
          - twitter_sentiment.app.properties
          - !ImportValue
            'Fn::Sub': '${paramServerStack}-esendpoint'